### PR TITLE
swarm

### PR DESCRIPTION
**Pull request by ahdinosaur**

### CODE REVIEW

**Comment by ahdinosaur** [comment]
so, am stuck!

status update:

- stack of 3 services, run in swarm mode
  - `buttcloud/butt-peer-server` never passes the healthcheck, the healthcheck says it times out after 30 seconds
  - `buttcloud/butt-landing` cannot connect to `buttcloud/butt-peer-server`
  - `buttcloud/butt-peer-server` works with `buttcloud/butt-peer-client` when publishing port 8008 in host mode, but not when publishing in the default ingress mode (since the peer servers will be on the various worker machines, we need to connect via any machine, or at least the manager machine)
  - `traefik` starts, lets encrypt seems to work maybe, is able to connect when publishing ports in host mode, in ingress mode need to force ipv4 (as in, `curl -4 http://localhost`).

so the main question, why does connecting to the peer server hang in the healthcheck or from the landing? what is different from the docker compose setup before, where this worked fine?

**Comment by austinfrey** [comment]
Since I'm a bit green with ssb not sure what all the logs mean but I figured I'd post them in case they were useful for others.
after running `STACK_NAME=example docker-stack deploy -c docker-compose example` i get the following outputs.

example_peer-server (when i can catch it trying to boot)
question about this one, should `port` be something other than `null`? or is that expected
```
example_peer-server.1.lzrd6icn6811@boot2docker    | {"level":30,"time":1523325415021,"pid":1,"hostname":"837a2b239732","id":"@9zlgQpfvn7tix6o8RHMzf2ttTB2dSSXAfpuqAaJX+1o=.ed25519","url":"net:example_peer-server:8008~shs:9zlgQpfvn7tix6o8RHMzf2ttTB2dSSXAfpuqAaJX+1o=","port":null,"env":"undefined","v":1}
example_peer-server.1.lzrd6icn6811@boot2docker    | {"level":30,"time":1523325415043,"msg":"SBOT 0 peers loaded from /home/node/.ssb/gossip.json","pid":1,"hostname":"837a2b239732","id":"@9zlgQpfvn7tix6o8RHMzf2ttTB2dSSXAfpuqAaJX+1o=.ed25519","v":1}

```
example_landing
```
example_landing.1.r2tv89z7m6ll@boot2docker    | {"level":50,"time":1523325468250,"msg":"could not connect to sbot","pid":1,"hostname":"604db90bec79","type":"Error","stack":"Error: could not connect to sbot\n    at /usr/src/app/node_modules/ssb-client/index.js:93:23\n    at /usr/src/app/node_modules/multiserver/compose.js:65:24\n    at Socket.<anonymous> (/usr/src/app/node_modules/multiserver/plugins/net.js:40:11)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)\n  Error: getaddrinfo ENOTFOUND example_peer-server example_peer-server:8008\n    at errnoException (dns.js:50:10)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)","v":1}
```
example_webproxy (debug output enabled with the `--debug=true` flag)
```
example_webproxy.1.vpp0rv3fmb0z@boot2docker    | time="2018-04-10T01:59:36Z" level=info msg="Traefik version v1.5.4 built on 2018-03-15_01:35:21PM" 
example_webproxy.1.vpp0rv3fmb0z@boot2docker    | time="2018-04-10T01:59:36Z" level=info msg="
example_webproxy.1.vpp0rv3fmb0z@boot2docker    | Stats collection is disabled.
example_webproxy.1.vpp0rv3fmb0z@boot2docker    | Help us improve Traefik by turning this feature on :)
example_webproxy.1.vpp0rv3fmb0z@boot2docker    | More details on: https://docs.traefik.io/basics/#collected-data
example_webproxy.1.vpp0rv3fmb0z@boot2docker    | " 
example_webproxy.1.vpp0rv3fmb0z@boot2docker    | time="2018-04-10T01:59:36Z" level=debug msg="Global configuration loaded {"LifeCycle":{"RequestAcceptGraceTimeout":0,"GraceTimeOut":10000000000},"GraceTimeOut":0,"Debug":true,"CheckNewVersion":true,"SendAnonymousUsage":false,"AccessLogsFile":"","AccessLog":null,"TraefikLogsFile":"","TraefikLog":null,"LogLevel":"DEBUG","EntryPoints":{"http":{"Network":"","Address":":80","TLS":null,"Redirect":null,"Auth":null,"WhitelistSourceRange":null,"Compress":false,"ProxyProtocol":null,"ForwardedHeaders":{"Insecure":true,"TrustedIPs":null}},"traefik":{"Network":"","Address":":8080","TLS":null,"Redirect":null,"Auth":null,"WhitelistSourceRange":null,"Compress":false,"ProxyProtocol":null,"ForwardedHeaders":{"Insecure":true,"TrustedIPs":null}}},"Cluster":null,"Constraints":[],"ACME":null,"DefaultEntryPoints":["http"],"ProvidersThrottleDuration":2000000000,"MaxIdleConnsPerHost":200,"IdleTimeout":0,"InsecureSkipVerify":false,"RootCAs":null,"Retry":null,"HealthCheck":{"Interval":30000000000},"RespondingTimeouts":null,"ForwardingTimeouts":null,"Web":null,"Docker":{"Watch":true,"Filename":"","Constraints":null,"Trace":false,"DebugLogGeneratedTemplate":false,"Endpoint":"unix:///var/run/docker.sock","Domain":"butt.nz","TLS":null,"ExposedByDefault":false,"UseBindPortIP":false,"SwarmMode":true},"File":null,"Marathon":null,"Consul":null,"ConsulCatalog":null,"Etcd":null,"Zookeeper":null,"Boltdb":null,"Kubernetes":null,"Mesos":null,"Eureka":null,"ECS":null,"Rancher":null,"DynamoDB":null,"ServiceFabric":null,"Rest":null,"API":{"EntryPoint":"traefik","Dashboard":true,"Debug":true,"CurrentConfigurations":null,"Statistics":null},"Metrics":null,"Ping":null}" 
example_webproxy.1.vpp0rv3fmb0z@boot2docker    | time="2018-04-10T01:59:36Z" level=info msg="Preparing server http &{Network: Address::80 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc4205bc4c0} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s" 
example_webproxy.1.vpp0rv3fmb0z@boot2docker    | time="2018-04-10T01:59:36Z" level=info msg="Preparing server traefik &{Network: Address::8080 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc4205bc560} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s" 
example_webproxy.1.vpp0rv3fmb0z@boot2docker    | time="2018-04-10T01:59:36Z" level=info msg="Starting provider *docker.Provider {"Watch":true,"Filename":"","Constraints":null,"Trace":false,"DebugLogGeneratedTemplate":false,"Endpoint":"unix:///var/run/docker.sock","Domain":"butt.nz","TLS":null,"ExposedByDefault":false,"UseBindPortIP":false,"SwarmMode":true}" 
example_webproxy.1.vpp0rv3fmb0z@boot2docker    | time="2018-04-10T01:59:36Z" level=info msg="Starting server on :80" 
example_webproxy.1.vpp0rv3fmb0z@boot2docker    | time="2018-04-10T01:59:36Z" level=info msg="Starting server on :8080" 
example_webproxy.1.vpp0rv3fmb0z@boot2docker    | time="2018-04-10T01:59:36Z" level=debug msg="Provider connection established with docker 18.03.0-ce (API 1.37)" 
example_webproxy.1.vpp0rv3fmb0z@boot2docker    | time="2018-04-10T01:59:36Z" level=debug msg="Could not load traefik.frontend.whitelistSourceRange labels" 
example_webproxy.1.vpp0rv3fmb0z@boot2docker    | time="2018-04-10T01:59:36Z" level=debug msg="Could not load traefik.frontend.entryPoints labels" 
example_webproxy.1.vpp0rv3fmb0z@boot2docker    | time="2018-04-10T01:59:36Z" level=debug msg="Could not load traefik.frontend.auth.basic labels" 
example_webproxy.1.vpp0rv3fmb0z@boot2docker    | time="2018-04-10T01:59:36Z" level=debug msg="Validation of load balancer method for backend backend-example-landing failed: invalid load-balancing method ''. Using default method wrr." 
example_webproxy.1.vpp0rv3fmb0z@boot2docker    | time="2018-04-10T01:59:36Z" level=debug msg="Configuration received from provider docker: {"backends":{"backend-example-landing":{"servers":{"server-example_landing-1":{"url":"http://10.0.0.12:8901","weight":0}},"loadBalancer":{"method":"wrr"}}},"frontends":{"frontend-Host-example-butt-nz-0":{"entryPoints":["http"],"backend":"backend-example-landing","routes":{"route-frontend-Host-example-butt-nz-0":{"rule":"Host:example.butt.nz"}},"passHostHeader":true,"priority":0,"basicAuth":[]}}}" 
example_webproxy.1.vpp0rv3fmb0z@boot2docker    | time="2018-04-10T01:59:36Z" level=debug msg="Creating frontend frontend-Host-example-butt-nz-0" 
example_webproxy.1.vpp0rv3fmb0z@boot2docker    | time="2018-04-10T01:59:36Z" level=debug msg="Wiring frontend frontend-Host-example-butt-nz-0 to entryPoint http" 
example_webproxy.1.vpp0rv3fmb0z@boot2docker    | time="2018-04-10T01:59:36Z" level=debug msg="Creating route route-frontend-Host-example-butt-nz-0 Host:example.butt.nz" 
example_webproxy.1.vpp0rv3fmb0z@boot2docker    | time="2018-04-10T01:59:36Z" level=debug msg="Creating backend backend-example-landing" 
example_webproxy.1.vpp0rv3fmb0z@boot2docker    | time="2018-04-10T01:59:36Z" level=debug msg="Creating load-balancer wrr" 
example_webproxy.1.vpp0rv3fmb0z@boot2docker    | time="2018-04-10T01:59:36Z" level=debug msg="Creating server server-example_landing-1 at http://10.0.0.12:8901 with weight 0" 
example_webproxy.1.vpp0rv3fmb0z@boot2docker    | time="2018-04-10T01:59:36Z" level=info msg="Server configuration reloaded on :80" 
example_webproxy.1.vpp0rv3fmb0z@boot2docker    | time="2018-04-10T01:59:36Z" level=info msg="Server configuration reloaded on :8080" 
```

**Comment by austinfrey** [comment]
Struggling to get this working as well. Removing the healthcheck allows the peer-server to boot, just like you mentioned. I even think the landing page service is able to connect, but for some reason you can't curl to it or view it in the browser. (i've removed traefik at this point, just to try and get the peer-server and landing page working and exposed the landing service port so i feel like it should be reachable at localhost:8901, but no luck!!) I do get the `Error: could not connect to sbot` sometimes, but i think this is only when the landing service starts before the peer-server is ready, but once it does i get the normal landing service output so I assume it's connected.

**Comment by ahdinosaur** [comment]
>  question about this one, should port be something other than null? or is that expected

yes this is my mistake, [this line](https://github.com/buttcloud/butt-peer/blob/8e838de2f50686a68409b7f15b6a4e40df9a26ee/server/index.js#L39) is a mistake, we're parsing a [`multiserver`](https://github.com/ssbc/multiserver) as a url.

> Removing the healthcheck allows the peer-server to boot, just like you mentioned.

nice.

> i feel like it should be reachable at localhost:8901, but no luck!!)

hmm!

**Comment by ahdinosaur** [comment]
my only hunch is that somehow the servers aren't binding to an externally available address, like `127.0.0.1` instead of `0.0.0.0`. or something along those lines.

**Pull request merged**
